---
title: "Run EconML (allocation period 2: panel data)"
author: "Shunkei Kakimoto"
output:
  html_document:
    number_sections: yes
    theme: flatly
    toc_float: yes
    toc: yes
    toc_depth: 3
geometry: margin=1in
---

```{r setup, include=FALSE}
library(knitr)
opts_knit$set(root.dir = "~/Dropbox/ResearchProject/HeterogeneousAllocation")

# library(here)
# opts_knit$set(root.dir = here())

knitr::opts_chunk$set(
  echo = TRUE,
  cache = FALSE,
  comment = NA,
  message = FALSE,
  warning = FALSE,
  tidy = FALSE,
  cache.lazy = FALSE,
  #--- figure ---#
  dpi = 400,
  fig.width = 7.5,
  fig.height = 5,
  out.width = "750px",
  out.height = "500px"
)

# /*===== Basic Packages  =====*/
# /*---- Data Wrangling ----*/
library(data.table)
library(tidyverse)
library(DescTools)
library(maps)

# /*---- Visualization ----*/
library(RColorBrewer)
library(patchwork)
library(ggplot2)
library(ggthemes)
library(ggpubr)
library(viridis)
library(grid)
library(gridExtra)
library(GGally)

# /*---- Model Summary ----*/
library(stats)
library(modelsummary)
library(flextable)
library(officer)
library(officedown)
library(gt)
```		

# Objective
+ Forcus on the data from 2008-2012 (this period is associated with the allocation period 2)
  * use panel data 


# Set up

```{r}
# setwd(here())
# /*===== R =====*/
source("./GitControlled/Codes/0_1_ls_packages.R")
source("./GitControlled/Codes/0_0_functions.R")

# /*===== python  =====*/
use_python("./myenv/bin/python")
use_virtualenv("./myenv/bin/activate_this.py")

source_python("./GitControlled/Codes/0_0_import_modules.py")
# source_python("./GitControlled/COdes/0_0_functions.py")

# /*===== Data (stage3, 2008- )=====*/
# --- panel data--- #
reg_data <- 
  readRDS("./Shared/Data/WaterAnalysis/comp_reg_dt.rds") %>%
  .[year %in% 2008:2012 & usage <= 40,]
```


# Preparation for regression analysis

+ Create training and testing dataset

## Variable Setting
```{r}
# /*===== control variables =====*/
cov_ls <- c(
	# --- weather --- #
	"pr_in", "gdd_in","pet_in",
	# --- soil --- #
  "silttotal_r", "claytotal_r", "slope_r", "ksat_r", "awc_r"
  )

all_vars <- c(cov_ls, 'usage', 'treat2', 'tr', 'year')
```

## Training Data
```{r}
# /*===== Training data  =====*/
fe_res <-
  feols(usage ~ 1 | wellid + year, data = reg_data) %>%
  fixef()

year_fe <- 
  data.table(
    year = names(fe_res$year) %>% as.numeric(),
    year_fe = fe_res$year
  )

ind_fe <- 
  data.table(
    wellid = names(fe_res$wellid) %>% as.numeric(),
    ind_fe = fe_res$wellid
  )

fe_data <-
  CJ(
    wellid = names(fe_res$wellid) %>% as.numeric, 
    year = 2007:2015
  ) %>%
  year_fe[., on = "year"] %>%
  ind_fe[., on = "wellid"]

reg_data_fe <- 
  fe_data[reg_data, on = c("year", "wellid")]
```



