---
title: "Run EconML on cross sectional data: year 2008-2015"
author: "Shunkei Kakimoto"
output:
  html_document:
    number_sections: yes
    theme: flatly
    toc_float: yes
    toc: yes
    toc_depth: 3
geometry: margin=1in
---

```{r setup, include=FALSE}
library(knitr)
library(here)
here::i_am("GitControlled/Codes/2_cross_sectional.rmd")

opts_chunk$set(
  echo = TRUE,
  cache = FALSE,
  message = FALSE,
  warning = FALSE, 
  cache.lazy = FALSE,
  #--- figure ---#
  dpi = 400,
  fig.width = 7.5,
  fig.height = 5,
  out.width = "750px",
  out.height = "500px"
)

# /*===== Basic Packages  =====*/
# /*---- Data Wrangling ----*/
library(data.table)
library(tidyverse)
library(DescTools)
library(maps)

# /*---- Visualization ----*/
library(RColorBrewer)
library(patchwork)
library(ggplot2)
library(ggthemes)
library(ggpubr)
library(viridis)
library(grid)
library(gridExtra)
library(GGally)

# /*---- Model Summary ----*/
library(stats)
library(modelsummary)
library(flextable)
library(officer)
library(officedown)
library(gt)
```

```{r include=F}
library(here)
```


# Set up

```{r}
library(here)
# /*===== R =====*/
source(here("GitControlled/Codes/0_1_ls_packages.R"))
source(here("GitControlled/Codes/0_0_functions.R"))

```


```{r, eval=F}
# /*===== python  =====*/

# --- Python module --- #
source_python(here("GitControlled/Codes/0_0_import_modules.py"))
# --- CF-DML --- #
source_python(here("GitControlled/Codes/run_cf_dml.py"))
# --- DR-ORF --- #
source_python(here("GitControlled/Codes/run_dr_orf.py"))
# --- DML-ORF --- #
source_python(here("GitControlled/Codes/run_dml_orf.py"))

# === for cross-section data === #
# --- DR-ORF --- #
source_python(here("GitControlled/Codes/run_dr_orf_agg.py"))
# --- DML-ORF --- #
source_python(here("GitControlled/Codes/run_dml_orf_agg.py"))

```


## Data

```{r}
# /*===== Data (allocation period 3, 2008-2012 )=====*/
# --- panel data--- #
reg_data <- readRDS(here("Shared/Data/WaterAnalysis/comp_reg_dt.rds")) %>%
  .[year %in% 2008:2012 & usage <= 40,]

# === Aggregate Data  === #
agg_reg_dt <- 
  reg_data %>%
  .[,.(
    usage = sum(usage),
    treat2 = mean(treat2),
    # --- soil --- #
    silttotal_r = mean(silttotal_r),
    claytotal_r = mean(claytotal_r),
    slope_r = mean(slope_r),
    ksat_r = mean(ksat_r),
    awc_r = mean(awc_r),
    # --- weather --- #    
    pr_in = sum(pr_in),
    pet_in = sum(pet_in),
    gdd_in = sum(gdd_in)
    ),by=wellid]
```




```{r, echo=F}

## Functions
# /*===========================================*/
#'=  Function for Data Preparation=
# /*===========================================*/
prep_data <- 
  function(data, het_vars){
  # data = agg_reg_dt; het_vars = c("pr_in", "gdd_in","pet_in")
  # data = agg_reg_dt; het_vars = "pr_in"

  # /*===== variables =====*/
  cov_ls <- c(
  # --- weather --- #
  "pr_in", "gdd_in","pet_in",
  # --- soil --- #
  "silttotal_r", "claytotal_r", "slope_r", "ksat_r", "awc_r"
  )

  #/*--------------------------------*/
  #' ## Training data
  #/*--------------------------------*/

  # --- dependent variable --- #
  Y <- data[, usage] %>% as.array() %>% unname()
  # --- treatment indicator --- #
  T <- data[, treat2] %>% as.array() %>% unname()
  # --- heterogeneous impact dirivers --- #
  X <- data[, ..het_vars] %>% as.matrix() %>% unname()
  # --- confounders/controls --- #
  W <- data[, ..cov_ls] %>% as.matrix() %>% unname()

  #/*--------------------------------*/
  #' ## Testing data
  #/*--------------------------------*/
  X_test <- 
    lapply(
      het_vars,
      function(x) gen_pred_data(data, het_vars, target_var = x)
      ) %>%
    bind_rows()
    # .[,!"target_var"] %>%
    # as.matrix() %>%
    # unname()

  return(
    list(Y = Y, X = X, T = T, W = W, X_test = X_test)
    )
}



# /*===========================================*/
#'=  Function to run EconML =
# /*===========================================*/

#/*--------------------------------*/
#' ## DR-ORF
#/*--------------------------------*/
run_DR_orf_comp <- function(data, het_vars) {
  # data=agg_reg_dt; het_vars= "pet_in"
  # data=agg_reg_dt; het_vars= c("pr_in", "gdd_in","pet_in")

  dt <- prep_data(data, het_vars)
  Y <- dt$Y
  T <- dt$T
  X <- dt$X
  W <- dt$W
  X_test <- 
    dt$X_test %>%
    .[,!"target_var"] %>%
    as.matrix() %>%
    unname()

  res_dr_orf <- 
    run_dr_orf(
    # run_dr_orf_agg(
      Y = Y,
      T = T,
      X = X,
      W = W,
      X_test = X_test
    )

  temp <-
    dt$X_test %>%
    melt(id.var='target_var') %>%
     .[target_var==variable,]

  res_X_test_drorf <- 
    data.table(
      x = temp[, value],
      pred_te = res_dr_orf[[1]] %>% c(),
      te_lower = res_dr_orf[[2]] %>% c(),
      te_upper = res_dr_orf[[3]] %>% c(),
      variable = dt$X_test[, target_var]
    )

  # ggplot(res_X_test_drorf) +
  #   geom_line(aes(x=x, y=pred_te)) +
  #   # geom_smooth(aes(x=x, y=pred_te), se = FALSE) +
  #   geom_ribbon(aes(x=x, ymin=te_lower, ymax=te_upper), alpha=0.4) +
  #   facet_grid(~variable, scale = "free")

  return(res_X_test_drorf)
}


#/*--------------------------------*/
#' ## DML-ORF
#/*--------------------------------*/
run_DML_orf_comp <- function(data, het_vars) {
  # data=agg_reg_dt; het_vars= "pet_in"
  # data=agg_reg_dt; het_vars= c("pr_in", "gdd_in","pet_in")
  dt <- prep_data(data, het_vars)
  Y <- dt$Y
  T <- dt$T
  X <- dt$X
  W <- dt$W
  X_test <- 
    dt$X_test %>%
    .[,!"target_var"] %>%
    as.matrix() %>%
    unname()

  #/*--------------------------------*/
  #' ## Regression Analysis
  #/*--------------------------------*/
  res_dml_orf <- 
    run_dml_orf(
    # run_dml_orf_agg(
      Y = Y,
      T = T,
      X = X,
      W = W,
      X_test = X_test
    )

  temp <-
    dt$X_test %>%
    melt(id.var='target_var') %>%
     .[target_var==variable,]

  res_X_test_dmlorf <- 
    data.table(
      x = temp[, value],
      pred_te = res_dml_orf[[1]] %>% c(),
      te_lower = res_dml_orf[[2]] %>% c(),
      te_upper = res_dml_orf[[3]] %>% c(),
      variable = dt$X_test[, target_var]
    )

  # ggplot(res_X_test_dmlorf) +
  #   geom_line(aes(x=x, y=pred_te)) +
  #   # geom_smooth(aes(x=x, y=pred_te), se = FALSE) +
  #   geom_ribbon(aes(x=x, ymin=te_lower, ymax=te_upper), alpha=0.4)

  return(res_X_test_dmlorf)
}

```


# Regression Analysis:


<!-- ## Estimate the Imapct of pet_in, gdd_in, and pr_in -->


```{r, eval = F, echo=F}
# === Run DR-ORF === #
agg_res_DR_orf_joint <- 
  run_DR_orf_comp(data=agg_reg_dt, het_vars = c("pr_in", "gdd_in","pet_in"))

saveRDS(agg_res_DR_orf_joint, here("Shared/Results/resRegression/agg_res_DR_orf_joint.rds"))

# saveRDS(agg_res_DR_orf_joint, here("Shared/Results/resRegression/agg_res_DR_orf_joint_lasso.rds"))

# saveRDS(agg_res_DR_orf_joint, here("Shared/Results/resRegression/agg_res_DR_orf_joint_aggfn.rds"))

# ggplot(agg_res_DR_orf_joint) +
#   geom_line(aes(x=x, y=pred_te)) +
#   geom_ribbon(aes(x=x, ymin=te_lower, ymax=te_upper), alpha=0.4) +
#   facet_grid(~variable, scale = "free")


# === Run DML-ORF === #
agg_res_DML_orf_joint <- 
  run_DML_orf_comp(data=agg_reg_dt, het_vars = c("pr_in", "gdd_in","pet_in"))

# saveRDS(agg_res_DML_orf_joint, here("Shared/Results/resRegression/agg_res_DML_orf_joint.rds"))


# ggplot(agg_res_DML_orf_joint) +
#   geom_line(aes(x=x, y=pred_te)) +
#   geom_ribbon(aes(x=x, ymin=te_lower, ymax=te_upper), alpha=0.4) +
#   facet_grid(~variable, scale = "free")
```


<!-- ## Results -->

```{r, echo=F, eval=F}
agg_res_DR_orf_joint <- 
  here("Shared/Results/resRegression/agg_res_DR_orf_joint.rds") %>%
  readRDS()

saveRDS(agg_res_DR_orf_joint, here("Shared/Results/resRegression/agg_res_DR_orf_joint_lasso.rds"))

agg_res_DML_orf_joint <-
  here("Shared/Results/resRegression/agg_res_DML_orf_joint.rds") %>%
  readRDS()

agg_res_joint <- 
  bind_rows(agg_res_DR_orf_joint, agg_res_DML_orf_joint, .id = "type") %>%
  .[,type:=ifelse(type==1, "DR-ORF", "DML-ORF")]

ggplot(agg_res_joint) +
  geom_line(aes(x=x, y=pred_te)) +
  geom_ribbon(aes(x=x, ymin=te_lower, ymax=te_upper), alpha=0.4) +
  facet_grid(type~variable, scale = "free_x")+
  labs(title = "Estimate the Impact of pet_in, gdd_in, and pr_in") +
  ylab("Treatment Effect (inches)")
```


---

## Estimate the Impact of pet_in, gdd_in, and pr_in, separately

```{r, eval = F}
# === Run DR-ORF === #
agg_res_DR_orf_sep <- 
  lapply(
    c("pr_in", "gdd_in","pet_in"), 
    function(x) run_DR_orf_comp(data=agg_reg_dt, het_vars = x)) %>%
  bind_rows()

saveRDS(agg_res_DR_orf_sep, here("Shared/Results/resRegression/agg_res_DR_orf_sep.rds"))

# Error: Error in py_call_impl(callable, dots$args, dots$keywords) : 
# ValueError: The original error: could not broadcast input array from shape (10,3,10) into shape (10,) This might be caused by too few sample in the tree leafs. Try increasing the min_leaf_size.


# ggplot(agg_res_DR_orf_sep) +
#   geom_line(aes(x=x, y=pred_te)) +
#   geom_ribbon(aes(x=x, ymin=te_lower, ymax=te_upper), alpha=0.4) +
#   facet_grid(~variable, scale = "free")


# === Run DML-ORF === #
agg_res_DML_orf_sep <- 
  lapply(c("pr_in", "gdd_in","pet_in"), 
  function(x) run_DML_orf_comp(data=agg_reg_dt, het_vars = x)) %>%
  bind_rows()

saveRDS(agg_res_DML_orf_sep, here("Shared/Results/resRegression/agg_res_DML_orf_sep.rds"))

# ggplot(agg_res_DML_orf_sep) +
#   geom_line(aes(x=x, y=pred_te)) +
#   geom_ribbon(aes(x=x, ymin=te_lower, ymax=te_upper), alpha=0.4) +
#   facet_grid(~variable, scale = "free")
```

## Results

```{r, echo=F}
# agg_res_DR_orf_sep <- 
#   here("Shared/Results/resRegression/agg_res_DR_orf_sep.rds") %>%
#   readRDS()

agg_res_DML_orf_sep <-
  here("Shared/Results/resRegression/agg_res_DML_orf_sep.rds") %>%
  readRDS()

# agg_res_sep <- 
#   bind_rows(agg_res_DR_orf_sep, agg_res_DML_orf_sep, .id = "type") %>%
#   .[,type:=ifelse(type==1, "DR-ORF", "DML-ORF")]


ggplot(agg_res_DML_orf_sep) +
  geom_line(aes(x=x, y=pred_te)) +
  geom_ribbon(aes(x=x, ymin=te_lower, ymax=te_upper), alpha=0.4) +
  facet_grid(~variable, scale = "free_x")+
  # facet_grid(type~variable, scale = "free_x")+
  labs(title = "Estimate the Impact of pet_in, gdd_in, and pr_in, separately") +
  ylab("Treatment Effect (inches)")
```




