---
title: "Run Accelerated Bayesian Causal Forest (XBCF)"
author: "Shunkei Kakimoto"
date: ""
output: html_document
---


```{r setup, include=FALSE}
library(knitr)
# library(here)
library(modelsummary)
library(data.table)
library(tidyverse)
library(maps)
library(flextable)
library(grf)
library(RColorBrewer)
library(patchwork)
library(plotly)
library(ggplot2)
library(ggthemes)
library(ggpubr)
library(viridis)
library(grid)
library(gridExtra)
library(flextable)
library(reticulate)
# knitr::opts_chunk$set(echo = TRUE)

# opts_knit$set(root.dir = here())
opts_knit$set(root.dir = "~/Dropbox/ResearchProject/HeterogeneousAllocation")

opts_chunk$set(
  fig.align = "center", 
  fig.retina = 5,
  warning = FALSE, 
  message = FALSE,
  cache = FALSE, # <-- T
  cache.lazy = FALSE,
  echo = TRUE
  )
```

# Objective

This is the test script using the codes of this [website](https://johaupt.github.io/bart/bayesian/causal%20inference/xbcf.html)


# Setup

```{python}
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from xbcausalforest import XBCF
```

# Data Generation Process

```{python}
# number of observations N and number of covariates k
N = 20000
k = 2
p_T =0.5

# Simulate data
def data_generating_process(X):
    # Define treatment assignment
    z = np.random.binomial(1, p_T, size=(N,))
    # Define treatment effects
    effect = 2 + 0.5*X[:,1] + 0.5*X[:,1]**2 - 0.5*X[:,0]**2 - 3*(X[:,0]>0) 
    # Define mean of the outcome
    mu = 100 + 5*X[:,0] - 5*X[:,1] + 2*X[:,0]**2 + 5*X[:,0]*X[:,1]
    # Calculate outcome 
    y = np.random.normal(mu, scale=2, size=(N,)) + z*effect
    return y, z, effect

X      = np.random.multivariate_normal([0,0], np.array([[1,0.1],[0.1,1]]), size=(N,))
X_test = np.random.multivariate_normal([0,0], np.array([[1,0.1],[0.1,1]]), size=(N,))

y, z, effect      = data_generating_process(X)
_, _, effect_test = data_generating_process(X_test)
```

```{r}
# Density plot of treatment effects
plot(density(py$effect))


# dt_y <- data.table(
#   z = py$z,
#   # x1 = py$X[,1],
#   # x2 = py$X[,2],
#   effect = py$effect,
#   y = py$y
#   ) %>%
#   .[,id:=1:nrow(.)] %>%
#   melt(id.var= c("id", "z"),  measure.vars = c("effect", "y"), value.name = "y_value") %>%
#   setnames("variable", "y_variable")

# dt_x <- data.table(
#   z = py$z,
#   x1 = py$X[,1],
#   x2 = py$X[,2]
#   # effect = py$effect,
#   # y = py$y
#   ) %>%
#   .[,id:=1:nrow(.)] %>%
#   melt(id.var= c("id", "z"),  measure.vars = c("x1", "x2"), value.name = "x_value") %>%
#   setnames("variable", "x_variable")

# dt_all <- dt_x[dt_y, on=c("id", "z")]

dt <- data.table(
  z = py$z,
  x1 = py$X[,1],
  x2 = py$X[,2],
  effect = py$effect,
  y = py$y
  )

x1_effect <- ggplot(dt)+
  geom_point(aes(x=x1, y=effect, color=factor(z)))

x1_y <- ggplot(dt)+
  geom_point(aes(x=x1, y=y, color=factor(z)))

x2_effect <- ggplot(dt)+
  geom_point(aes(x=x2, y=effect, color=factor(z)))

x2_y <- ggplot(dt)+
  geom_point(aes(x=x2, y=y, color=factor(z)))


grid.arrange(x1_y, x2_y, x1_effect, x2_effect, ncol=2)
```

# Accelerated Bayesian Causal Forest

## Build Trees

```{python}
NUM_TREES_PR  = 200
NUM_TREES_TRT = 100

xbcf = XBCF(
    #model="Normal",
    parallel=True, 
    num_sweeps=50, 
    burnin=15,
    max_depth=250,
    num_trees_pr=NUM_TREES_PR,
    num_trees_trt=NUM_TREES_TRT,
    num_cutpoints=100,
    Nmin=1,
    #mtry_pr=X1.shape[1], # default 0 seems to be 'all'
    #mtry_trt=X.shape[1], 
    tau_pr = 0.6 * np.var(y)/NUM_TREES_PR, #0.6 * np.var(y) / /NUM_TREES_PR,
    tau_trt = 0.1 * np.var(y)/NUM_TREES_TRT, #0.1 * np.var(y) / /NUM_TREES_TRT,
    alpha_pr= 0.95, # shrinkage (splitting probability)
    beta_pr= 2, # shrinkage (tree depth)
    alpha_trt= 0.95, # shrinkage for treatment part
    beta_trt= 2,
    p_categorical_pr = 0,
    p_categorical_trt = 0,
    standardize_target=True, # standardize y and unstandardize for prediction
         )

z= z.astype('int32')


xbcf.fit(
    x_t=X, # Covariates treatment effect
    x=X, # Covariates outcome (including propensity score)
    y=y,  # Outcome
    z=z, # Treatment group
)
```

## Prediction

```{python}
tau_xbcf = xbcf.predict(X_test, return_mean=True)
```

















