---
title: "Test DML ORF"
author: "Shunkei Kakimoto"
date: ""
output: html_document
---


```{r setup, include=FALSE}
library(knitr)
# library(here)
library(modelsummary)
library(data.table)
library(tidyverse)
library(maps)
library(flextable)
library(sf)
library(RColorBrewer)
library(patchwork)
library(plotly)
library(ggplot2)
library(ggthemes)
library(ggpubr)
library(viridis)
library(grid)
library(gridExtra)
library(flextable)
library(reticulate)
library(recipes)   # for data preprocessing
# knitr::opts_chunk$set(echo = TRUE)

# opts_knit$set(root.dir = here())
opts_knit$set(root.dir = "~/Dropbox/ResearchProject/HeterogeneousAllocation")

opts_chunk$set(
  fig.align = "center", 
  fig.retina = 5,
  warning = FALSE, 
  message = FALSE,
  cache = FALSE, # <-- T
  cache.lazy = FALSE,
  echo = TRUE
  )
```


```{r}
#--- reticulate ---#
use_python("./myenv/bin/python")
use_virtualenv("./myenv/bin/activate_this.py")
```

```{python}
# Main imports
from econml.orf import DMLOrthoForest, DROrthoForest
from econml.dml import CausalForestDML
from econml.sklearn_extensions.linear_model import WeightedLassoCVWrapper, WeightedLasso, WeightedLassoCV

# Helper imports
import numpy as np
from itertools import product
from sklearn.linear_model import Lasso, LassoCV, LogisticRegression, LogisticRegressionCV
import matplotlib.pyplot as plt

# %matplotlib inline
```

## Data

```{python}
# A few more imports
# import os
# import pandas as pd
# import urllib.request
# from sklearn.preprocessing import StandardScaler
```

```{python}
# Import the data
# file_name = "oj_large.csv"

# if not os.path.isfile(file_name):
#     print("Downloading file (this might take a few seconds)...")
#     urllib.request.urlretrieve("https://msalicedatapublic.blob.core.windows.net/datasets/OrangeJuice/oj_large.csv", file_name)
# oj_data = pd.read_csv(file_name)
# oj_data.head()


# # Prepare data
# Y = oj_data['logmove'].values
# T = np.log(oj_data["price"]).values
# scaler = StandardScaler()

# W1 = scaler.fit_transform(oj_data[[c for c in oj_data.columns if c not in ['price', 'logmove', 'brand', 'week', 'store']]].values)
# W2 = pd.get_dummies(oj_data[['brand']]).values
# W = np.concatenate([W1, W2], axis=1)
# X = oj_data[['INCOME']].values
```


# Load the orange juice dataset

```{r}

# Read from file
# oj_raw <- read_csv(here("data", "oj_large.csv"))

# Alternatively, read from the web
oj_raw <- read_csv("https://msalicedatapublic.blob.core.windows.net/datasets/OrangeJuice/oj_large.csv")
```

## Preprocessing

```{r}

oj_rec <- recipe(logmove ~ ., data = oj_raw) %>% 
  step_normalize(
    INCOME, AGE60, EDUC, ETHNIC, INCOME,
    HHLARGE, WORKWOM, HVAL150, SSTRDIST,
    SSTRVOL, CPDIST5, CPWVOL5
  ) %>% 
  step_dummy(brand, one_hot = TRUE) %>% 
  step_log(price) %>% 
  prep() %>% 
  juice()

head(oj_rec)

```


```{r}

Y <- oj_rec %>%
  pull(logmove) %>%
  as.array() %>% 
  unname()
  
T <- oj_rec %>%
  pull(price) %>%
  as.array() %>% 
  unname()

X <- oj_rec %>%
  select(INCOME) %>%
  as.matrix() %>% 
  unname()

W <- oj_rec %>%
  select(AGE60:CPWVOL5, starts_with("brand")) %>%
  as.matrix() %>% 
  unname()
```

Generate test data
```{r}

min_income <- -1
max_income <- 1
delta      <- (max_income - min_income) / 100

X_test <- seq(max_income, min_income, -delta) %>%
  as.matrix()

repl_python()
```


## Estimate CATE

```{python}
# Define some parameters
n_trees = 1000
min_leaf_size = 50
max_depth = 20
subsample_ratio = 0.04

est = DMLOrthoForest(
        n_trees=n_trees, min_leaf_size=min_leaf_size, max_depth=max_depth, 
        subsample_ratio=subsample_ratio,
        model_T=Lasso(alpha=0.1),
        model_Y=Lasso(alpha=0.1),
        model_T_final=WeightedLassoCVWrapper(cv=3), 
        model_Y_final=WeightedLassoCVWrapper(cv=3)
       )


est.fit(r.Y, r.T, X=r.X, W=r.W)

te_pred = est.effect(r.X_test)

# Calculate default (95%) marginal confidence intervals for the test data
te_upper, te_lower = est.const_marginal_effect_interval(r.X_test)
```


```{r}
cate_effect <- tibble("X_test" = X_test, "te_pred" = py$te_pred)

cate_effect %>% 
  ggplot(aes(X_test, te_pred)) +
  geom_line() +
  labs(
    x = "Scale(Income)",
    y = "Orange Juice Elasticity",
    title = "Orange Juice Elasticity vs Income"
  )
```


```{r}
cate_effect_interval <- cate_effect %>% 
  mutate(
    te_pred_down = py$te_lower,
    te_pred_up   = py$te_upper
  )

# head(cate_effect_interval)


cate_effect_interval %>% 
  ggplot(aes(X_test, te_pred)) +
  geom_ribbon(aes(ymin = te_pred_down, ymax = te_pred_up),
              fill = "grey70") +
  geom_line() +
  labs(
    x = "Scale(Income)",
    y = "Orange Juice Elasticity",
    title = "Orange Juice Elasticity vs Income",
    fill  = "1-99% CI"
  )

```