---
title: "Run ORF"
author: "Shunkei Kakimoto"
date: ""
output: html_document
---


```{r setup, include=FALSE}
library(knitr)
library(here)
library(modelsummary)
library(data.table)
library(tidyverse)
library(maps)
library(flextable)
library(sf)
library(RColorBrewer)
library(patchwork)
library(plotly)
library(ggplot2)
library(ggthemes)
library(ggpubr)
library(viridis)
library(grid)
library(gridExtra)
library(flextable)
library(reticulate)
# knitr::opts_chunk$set(echo = TRUE)

opts_knit$set(root.dir = here())

opts_chunk$set(
  fig.align = "center", 
  fig.retina = 5,
  warning = FALSE, 
  message = FALSE,
  cache = FALSE, # <-- T
  cache.lazy = FALSE,
  echo = F
  )
```



```{r}
here()
#--- reticulate ---#
use_python("/Users/shunkeikakimoto/Dropbox/ResearchProject/HeterogeneousAllocation/myenv/bin/python")
use_virtualenv("/Users/shunkeikakimoto/Dropbox/ResearchProject/HeterogeneousAllocation/myenv/bin/activate_this.py")

py_config()
```


# Data

```{r}
#--- sourcing R.function ---#
source(here('./Codes/Functions/functions.R'))
```

```{r}
#--- import the data ---# (yearly data)
ir_data <- readRDS(here('Shared/Data/ir_reg.rds')) %>%
  .[source %in% c('Meter','METER','metered'),] %>%
  .[,trs:=paste(twnid,rngid,section,sep='_')] %>%
  .[,tr:=paste(twnid,rngid,sep='_')] %>%
  .[,phase1:=ifelse(year<2008,1,0)] %>%
  .[,phase2:=ifelse(year>=2008,1,0)]


#--- data ---#
data_w_W1 <- ir_data %>%
  .[Low_Tri_5mi==1, ] %>%
  .[,`:=`(
    #--- LR east vs TB (2007-2008)---#
    treat1e=ifelse(phase1==1 & nrdname=='Lower Republican' & in_east==1, 1, 0),
    #--- LR west vs TB (2007 - 2008) ---#
    treat1w=ifelse(phase1==1 & nrdname=='Lower Republican' & in_west==1, 1, 0),
    #--- LR vs TB (2008 - 2015)---#
    treat2=ifelse(((nrdname=='Lower Republican' & phase2==1) | (t5r22==1& year>=2009)), 1, 0)
    )] %>%
  .[,`:=`(
    mean_precip=mean(precip_in),
    mean_gdd=mean(gdd_in),
    mean_tmin=mean(tmin_in),
    mean_tmax=mean(tmax_in)
  ),by=wellid]



cov_ls <- c('precip_in', 'tmin_in', 'tmax_in', 'gdd_in',
  'silt_pct', 'clay_pct', 'slope', 'kv', 'awc')

all_vars <- c(cov_ls,'usage','treat2', 'tr', 'year')


###--- W1 case 3: 11 inches (LR) vs no limit (TB) (2008 - 2015) ---###
data_reg_case3 <- data_w_W1 %>%
  .[year >= 2008, ] %>%
  .[,..all_vars] %>% 
  .[usage<=40,] %>% # Why?? -> make upper limit
  .[,tr_year:=factor(paste0(tr,year))] %>% 
  na.omit()


###--- training dataset ---###
Y <- data_reg_case3[,usage]
X <- data_reg_case3[,cov_ls,with=FALSE]
W <- data_reg_case3[,treat2]

Y_array <- Y %>% as.array() %>% unname()
X_array <- X %>% as.matrix() %>% unname()
W_array <- W %>% as.array() %>% unname()
```


