---
title: "Report: Estimating the Impact of Groundwater Allocation Policies on Irrigation Behavior"
author: "Shunkei Kakimoto"
output:
  html_document:
    number_sections: yes
    theme: flatly
    toc_float: yes
    toc: yes
    toc_depth: 3
geometry: margin=1in
---

```{r setup, include=FALSE}
library(knitr)
library(here)
here::i_am("GitControlled/Codes/2_grf_cf_analysis.rmd")

opts_chunk$set(
  echo = TRUE,
  cache = FALSE,
  message = FALSE,
  warning = FALSE, 
  cache.lazy = FALSE,
  #--- figure ---#
  dpi = 400,
  fig.width = 7.5,
  fig.height = 5,
  out.width = "750px",
  out.height = "500px"
)

# /*===== Basic Packages  =====*/
# /*---- Data Wrangling ----*/
library(data.table)
library(tidyverse)
library(DescTools)
library(maps)

# /*---- Visualization ----*/
library(RColorBrewer)
library(patchwork)
library(ggplot2)
library(ggthemes)
library(ggpubr)
library(viridis)
library(grid)
library(gridExtra)
library(GGally)

# /*---- Model Summary ----*/
library(stats)
library(modelsummary)
library(flextable)
library(officer)
library(officedown)
library(gt)
```

```{r include=F}
library(here)
```


# Results

```{r}
# === setup === #
library(here)
source(here("GitControlled/Codes/0_1_ls_packages.R"))
source(here("GitControlled/Codes/0_0_functions.R"))

# /*===== Data =====*/
reg_data <- 
  here("Shared/Data/WaterAnalysis/comp_reg_dt.rds") %>%
  readRDS() %>%
  # .[year==2015 & usage <= 40,]
  .[year %in% 2008:2012 & usage <= 40,] %>%
  .[,tr_year:=factor(paste0(tr,year))] %>%
  .[,trs_year:=factor(paste0(trs,year))]

# agg_reg_data <-
#   copy(reg_data) %>%
#   .[year == 2012] %>%
#   # .[year %in% 2008:2009] %>%
#   # .[year %in% c(2008:2009, 2011:2012)] %>%
#   .[,.(
#     usage = sum(usage),
#     treat2 = mean(treat2),
#     # --- soil --- #
#     silttotal_r = mean(silttotal_r),
#     claytotal_r = mean(claytotal_r),
#     slope_r = mean(slope_r),
#     ksat_r = mean(ksat_r),
#     awc_r = mean(awc_r),
#     # --- weather --- #    
#     pr_in = sum(pr_in),
#     pet_in = sum(pet_in),
#     gdd_in = sum(gdd_in),
#     # --- tr --- #
#     tr = tr
#     ),by=wellid] %>%
#   unique(.,by="wellid")


#/*--------------------------------*/
#' ## Preparation
#/*--------------------------------*/
# /*===== control variables =====*/
# remove gdd_in
cov_ls <- c(
  # --- weather --- #
  "pr_in","pet_in",
  # --- soil --- #
  "silttotal_r", "claytotal_r", "slope_r", "ksat_r", "awc_r"
  )


data <- reg_data
# data <- agg_reg_data

dummies <-
  fastDummies::dummy_cols(data, select_columns = "ID") %>%
  .[, paste0("ID_", unique(data$ID)), with=FALSE] %>%
  as.matrix() %>%
  .[, -1]

# /*===== Training Dataset  =====*/
# --- dependent variable --- #
Y <- data[, usage]
# --- treatment indicator --- #
T <- data[, treat2]
# --- features --- #
X <- data[, ..cov_ls]
# X_full <- X %>% as.matrix() %>% cbind(., dummies)

# --- cluster  --- #
cl_var <- data[,tr_year]

# cl_var <- data[,tr] %>% as.factor()

#/*--------------------------------*/
#' ## 1st CF
#/*--------------------------------*/
set.seed(23456)
forest_W <- regression_forest(X, T, num.trees = 4000, clusters = cl_var)
W_hat <- predict(forest_W)$predictions

forest_Y <- regression_forest(X, Y, num.trees = 4000, clusters = cl_var)
Y_hat <- predict(forest_Y)$predictions

cf_raw <- causal_forest(
  X=X,
  Y=Y,
  W=T, 
  # Y.hat = Y_hat, 
  # W.hat = W_hat,
  clusters = cl_var,
  tune.parameters = "all",
  num.trees = 4000
)

varimp = variable_importance(cf_raw)
selected_vars = which(varimp > mean (varimp))
# selected_vars = which(varimp/mean(varimp) > 0.2)
se_cov <- data[,cov_ls[selected_vars], with=FALSE]

vis_cf_raw_pr2 <- gen_impact_viz(
  cf_res= cf_raw,
  data_base=data,
  treat_var='treat2',
  var_ls= cov_ls,
  var_ls_int = cov_ls
)

#/*--------------------------------*/
#' ## 2nd CF
#/*--------------------------------*/
cf_res <- causal_forest(
  X=se_cov,
  Y=Y,
  W=T, 
  Y.hat = Y_hat, 
  W.hat = W_hat,
  clusters = cl_var,
  sample.fraction = 0.4,
  num.trees = 4000,
  tune.parameters = "all",
  # tune.parameters = c(""),
)

#/*--------------------------------*/
#' ## Visualization
#/*--------------------------------*/
vis_cf_res_pr2 <- gen_impact_viz(
  cf_res= cf_res,
  data_base=data,
  treat_var='treat2',
  var_ls= cov_ls[selected_vars],
  var_ls_int = cov_ls[selected_vars]
)
 ```

## Compare
```{r, echo=F}
vis_cf_raw_pr2

vis_cf_res_pr2
```

# Aggregated Data
```{r, echo=F}
agg_reg_data <-
  copy(reg_data) %>%
  .[year == 2012] %>%
  # .[year %in% 2008:2009] %>%
  # .[year %in% c(2008:2009, 2011:2012)] %>%
  .[,.(
    usage = sum(usage),
    treat2 = mean(treat2),
    # --- soil --- #
    silttotal_r = mean(silttotal_r),
    claytotal_r = mean(claytotal_r),
    slope_r = mean(slope_r),
    ksat_r = mean(ksat_r),
    awc_r = mean(awc_r),
    # --- weather --- #    
    pr_in = sum(pr_in),
    pet_in = sum(pet_in),
    gdd_in = sum(gdd_in),
    # --- tr --- #
    tr = tr
    ),by=wellid] %>%
  unique(.,by="wellid")


#/*--------------------------------*/
#' ## Preparation
#/*--------------------------------*/
# /*===== control variables =====*/
# remove gdd_in
cov_ls <- c(
  # --- weather --- #
  "pr_in","pet_in",
  # --- soil --- #
  "silttotal_r", "claytotal_r", "slope_r", "ksat_r", "awc_r"
  )

data <- agg_reg_data

# /*===== Training Dataset  =====*/
# --- dependent variable --- #
Y <- data[, usage]
# --- treatment indicator --- #
T <- data[, treat2]
# --- features --- #
X <- data[, ..cov_ls]
# X_full <- X %>% as.matrix() %>% cbind(., dummies)

# --- cluster  --- #
cl_var <- data[,tr] %>% factor()

#/*--------------------------------*/
#' ## 1st CF
#/*--------------------------------*/
set.seed(23456)
# forest_W <- regression_forest(X, T, num.trees = 4000, clusters = cl_var)
# W_hat <- predict(forest_W)$predictions

# forest_Y <- regression_forest(X, Y, num.trees = 4000, clusters = cl_var)
# Y_hat <- predict(forest_Y)$predictions

cf_raw <- causal_forest(
  X=X,
  Y=Y,
  W=T, 
  # Y.hat = Y_hat, 
  # W.hat = W_hat,
  clusters = cl_var,
  tune.parameters = "all",
  num.trees = 4000
)

varimp = variable_importance(cf_raw)
selected_vars = which(varimp > mean (varimp))
# selected_vars = which(varimp/mean(varimp) > 0.2)
se_cov <- data[,cov_ls[selected_vars], with=FALSE]

vis_cf_raw <- gen_impact_viz(
  cf_res= cf_raw,
  data_base=data,
  treat_var='treat2',
  var_ls= cov_ls,
  var_ls_int = cov_ls
)


#/*--------------------------------*/
#' ## 2nd CF
#/*--------------------------------*/
cf_res <- causal_forest(
  X=se_cov,
  Y=Y,
  W=T, 
  # Y.hat = Y_hat, 
  # W.hat = W_hat,
  clusters = cl_var,
  sample.fraction = 0.4,
  num.trees = 4000,
  tune.parameters = "all",
  # tune.parameters = c(""),
)

#/*--------------------------------*/
#' ## Visualization
#/*--------------------------------*/
vis_cf_res_pr2 <- gen_impact_viz(
  cf_res= cf_res,
  data_base=data,
  treat_var='treat2',
  var_ls= cov_ls[selected_vars],
  var_ls_int = cov_ls[selected_vars]
)
```

```{r, echo=F}
vis_cf_raw

vis_cf_res_pr2
```


# Question
+ The problem is that the regression analysis using the data 2008-2012 (which corresponds to the allocation period 2) does not show strong heterogeneity in weather variables. <br/>

+ **Why?**

```{r}
reg_data[,.N, by=.(year, nrdname)] %>% .[order(year,nrdname)]
```


```{r}
# === Wawter use comparison between LR and TB  === #
ggplot() +
  geom_boxplot(data = reg_data, aes(x=year, y= usage, group= interaction(nrdname, year), fill= nrdname))

# === Weather variable comparison between LR and TB === #

annual_mean <- 
  reg_data %>%
  .[,.(
    pr_in = mean(pr_in),
    pet_in = mean(pet_in),
    gdd_in = mean(gdd_in)
    ), by = .(year, nrdname)] %>%
  melt(id.vars = c("year", "nrdname"))


ggplot() +
  geom_line(data = annual_mean, aes(x=year, y= value, color= nrdname)) +
  facet_grid(variable~., scales = "free")
```