---
title: "Causal Forest Analysis"
author: "Shunkei Kakimoto"
output:
  html_document:
    number_sections: yes
    theme: flatly
    toc_float: yes
    toc: yes
    toc_depth: 3
geometry: margin=1in
---

```{r setup, include=FALSE}
library(knitr)
library(here)

here::i_am("GitControlled/Codes/run_CF.rmd")

knitr::opts_chunk$set(
  echo = TRUE,
  cache = FALSE,
  comment = NA,
  message = FALSE,
  warning = FALSE,
  tidy = FALSE,
  cache.lazy = FALSE,
  #--- figure ---#
  dpi = 400,
  fig.width = 7.5,
  fig.height = 5,
  out.width = "750px",
  out.height = "500px"
)

# /*===== Basic Packages  =====*/
# /*---- Data Wrangling ----*/
library(data.table)
library(tidyverse)
library(DescTools)
library(maps)

# /*---- Visualization ----*/
library(RColorBrewer)
library(patchwork)
library(ggplot2)
library(ggthemes)
library(ggpubr)
library(viridis)
library(grid)
library(gridExtra)
library(GGally)

# /*---- Model Summary ----*/
library(stats)
library(modelsummary)
library(flextable)
library(officer)
library(officedown)
library(gt)
```

```{r, include=F}
library(grf)
```

# Preparation

# Data
```{r}
# library(here)
# setwd(here())

# /*===== R =====*/
source(here("GitControlled/Codes/0_1_ls_packages.R"))
source(here("GitControlled/Codes/0_0_functions.R"))

# /*===== Data (stage3, 2008- )=====*/
# --- panel data--- #
reg_data <- readRDS(here("Shared/Data/WaterAnalysis/comp_reg_dt.rds")) %>%
  .[year>=2008 & usage <= 40,]
```


## Variables to be included
```{r}
# /*===== control variables =====*/
cov_ls <- c(
	# --- weather --- #
	"pr_in", "gdd_in","pet_in",
	# --- soil --- #
  	"silttotal_r", "claytotal_r", "slope_r", "ksat_r", "awc_r"
  )

all_vars <- c(cov_ls, 'usage', 'treat2', 'tr', 'year')
```

# Run CF

```{r}
# /*===========================================*/
#'=  Setup: Training Data =
# /*===========================================*/

# /*===== Training Dataset  =====*/
# --- dependent variable --- #
Y <- reg_data[, usage]
# --- treatment indicator --- #
T <- reg_data[, treat2]
# --- features --- #
X <- reg_data[, ..cov_ls]

# --- cluster  --- #
cl_var <- 
  data.table::copy(reg_data) %>%
  .[,tr_year:=factor(paste0(tr,year))] %>%
  .[,tr_year]


# /*===========================================*/
#'=  Run CF =
# /*===========================================*/

forest_W <- boosted_regression_forest(X, T, tune.parameters = "all")
W_hat <- predict(forest_W)$predictions
forest_Y <- boosted_regression_forest(X, Y, tune.parameters = "all")
Y_hat <- predict(forest_Y)$predictions

res_cf <- causal_forest(
  X=X, 
  Y=Y,
  W=T, 
  Y.hat = Y_hat, 
  W.hat = W_hat,
  clusters = cl_var,
  tune.parameters = "all",
)
```

# Results

```{r}
# /*===== Visualization: TE estimates =====*/
gen_impact_viz(
  cf_res= res_cf,
  data_base=reg_data,
  treat_var='treat2',
  var_ls= cov_ls,
  var_ls_int = cov_ls
)
```